export default {
  ru: {
    valueHeader:'Значение',
    valueOne:'Мин',
    valueTwo:'Макс',
    recommendedHeaderGreen:'Рекомендация зеленого статуса',
    for:'для',
    recommendedHeaderOrange:'Рекомендация оранжевого статуса',
    recommendedHeaderRed:'Рекомендация красного статуса',
    young:'Молодой ',
    old:'Взрослый ',
    preparationsHeaderGreen:'Препараты зеленого статуса',
    preparationsHeaderOrange:'Препараты оранжевого статуса',
    preparationsHeaderRed:'Препараты красного статуса',
    recommendedValidText:'Рекомендация не должно быть пустым',
    editNavigationRu:'Редактировать на русском',
    editNavigationEn:'Редактировать на английском',
    name: "Название",
    author: "Автор",
    subject: "Тематика",
    date_add: "Дата добавления",
    turnOnOff: 'Выкл/Вкл',
    header_edit: "Редактировать Осе",
    publication:'Публикацию',
    nameValid:'Название не должно быть пустым',
    authorValid:'Автор не должно быть пустым',
    fileValid:'Файл должен быть добавлен',
    fileMaxSizeValid:'Файл должен быть меньше 20 мб ',
    total: "Всего",
    inRu: "на русском",
    inEn: "на английском",
    section: "Название",
    ingredient: "Ингредиент",
    picture: "Картинка",
    data: "Информация о Публикации",
    text: "Текст",
    literatureLink: "Ссылка на литературу",
    question: "Вопрос",
    variants: "Варианты",
    answerVariants: "Вариант ответа",
    language: "Язык",
    save: "Сохранить изменения",
    cancel: "Отменить",
    delete: "Удалить",
    deleteTitle: "Удаление глоссарий",
    deleteText: "Вы уверенны что хотите удалить глоссарий? Все данные будут удалены",
    questionData: "Данные вопроса",
    creationDate: "Дата создания",
    sectionData: "Данные раздела",
    number: "Номер",
    answer: "Ответ",
    point: "Балл",
    noVariants: "Нет вариантов",
  },
  en: {
    valueHeader:'Meaning',
    valueOne:'Min',
    valueTwo:'Max',
    recommendedHeaderGreen:'Green status recommendation',
    recommendedHeaderOrange:'Orange status recommendation',
    recommendedHeaderRed:'Red status recommendation',
    for:'for',
    young:'Young ',
    old:'Adult ',
    preparationsHeaderGreen:'Green Status Products',
    preparationsHeaderOrange:'Orange Status Products',
    preparationsHeaderRed:'Red Status Products',
    recommendedValidText:'Recommendation must not be empty',
    name: "Name",
    editNavigationRu:'Edit in Russian',
    editNavigationEn:'Edit in English',
    author: "Author",
    subject: "Subject",
    date_add: "Add date",
    turnOnOff: 'Off/On',
    header_edit: "Edit Axes",
    publication:'Publication',
    nameValid:'Name must not be empty',
    authorValid:'Author must not be empty',

    fileValid:'The file must be added',
    fileMaxSizeValid: 'The file must be less than 20 mb',
    total: "Total",
    inRu: "in Russian",
    inEn: "in English",
    section: "Name",
    ingredient: "Ingredient",
    picture: "Picture",
    data: "Publication Information",
    text: "Text",
    literatureLink: "Literature link",
    question: "Question",
    variants: "Variants",
    answerVariants: "Possible answer",
    language: "Langauge",
    save: "Save changes",
    cancel: "Cancel",
    delete: "Delete",
    deleteTitle: "Delete glossary",
    deleteText: "Do you want to delete the glossary? All the data will be deleted",
    questionData: "Question data",
    creationDate: "Creation date",
    sectionData: "Section data",
    number: "N",
    answer: "Answer",
    point: "Point",
    noVariants: "No variants",
  },
};
