export default {
  ru: {
    inRu: "на русском",
    inEn: "на английском",
    total: "Всего",
    name: "Имя",
    author: "Автор",
    file: "Файл",
    delete: "Удалить",
    seminarData: "Данные семинара",
    authorData: "Данные автора",
    surname: "Фамилия",
    tel: "Номер телефона",
    createdAt: "Дата создания",
    save: "Сохранить изменения",
    cancel: "Отменить",
    confirm: "Подтвердить",
    deleteTitle: "Удаление семинар",
    deleteText:
      "Вы уверенны что хотите удалить семинар? Все данные будут удалены",
  },
  en: {
    inRu: "in Russian",
    inEn: "in English",
    total: "Total",
    name: "Name",
    author: "Author",
    file: "File",
    delete: "Delete",
    seminarData: "Seminar Data",
    authorData: "Author data",
    surname: "Surname",
    tel: "Phone number",
    createdAt: "Created At",
    save: "Save changes",
    cancel: "Cancel",
    confirm: "Confirm",
    deleteTitle: "Deleting a seminar",
    deleteText:
      "Are you sure you want to delete a seminar? All data will be deleted",
  },
};
