export default {
  ru: {
    inRu: "на русском",
    inEn: "на английском",
    total: "Всего",
    name: "Имя",
    delete: "Удалить",
    section: "Раздел",
    question: "Вопрос",
    variants: "Варианты",
    answerVariants: "Вариант ответа",
    language: "Язык",
    save: "Сохранить изменения",
    cancel: "Отменить",
    deleteTitle: "Удаление опроса",
    deleteText:
      "Вы уверенны что хотите удалить опрос? Все данные будут удалены",
    questionData: "Данные вопроса",
    creationDate: "Дата создания",
    sectionData: "Данные раздела",
    number: "Номер",
    answer: "Ответ",
    point: "Балл",
    noVariants: "Нет вариантов",
    edit: "Редактировать",
    max_point: "Макс балл",
  },
  en: {
    inRu: "in Russian",
    inEn: "in English",
    total: "Total",
    name: "Name",
    delete: "Delete",
    section: "Section",
    question: "Question",
    variants: "Variants",
    answerVariants: "Possible answer",
    language: "Langauge",
    save: "Save changes",
    cancel: "Cancel",
    deleteTitle: "Delete quiz",
    deleteText: "Do you want to delete the quiz? All the data will be deleted",
    questionData: "Question data",
    creationDate: "Creation date",
    sectionData: "Section data",
    number: "N",
    answer: "Answer",
    point: "Point",
    noVariants: "No variants",
    edit: "Edit",
    max_point: "Max Point"
  },
};
