export default {
  ru: {
    total: "Всего",
    inRu: "на русском",
    inEn: "на английском",
    section: "Раздел",
    ingredient: "Ингредиент",
    picture: "Картинка",
    data: "Данные",
    text: "Текст",
    literatureLink: "Ссылка на литературу",
    question: "Вопрос",
    variants: "Варианты",
    answerVariants: "Вариант ответа",
    language: "Язык",
    save: "Сохранить изменения",
    cancel: "Отменить",
    delete: "Удалить",
    deleteTitle: "Удаление глоссарий",
    deleteText:
      "Вы уверенны что хотите удалить глоссарий? Все данные будут удалены",
    questionData: "Данные вопроса",
    creationDate: "Дата создания",
    sectionData: "Данные раздела",
    number: "Номер",
    answer: "Ответ",
    point: "Балл",
    noVariants: "Нет вариантов",
  },
  en: {
    total: "Total",
    inRu: "in Russian",
    inEn: "in English",
    section: "Section",
    ingredient: "Ingredient",
    picture: "Picture",
    data: "Data",
    text: "Text",
    literatureLink: "Literature link",
    question: "Question",
    variants: "Variants",
    answerVariants: "Possible answer",
    language: "Langauge",
    save: "Save changes",
    cancel: "Cancel",
    delete: "Delete",
    deleteTitle: "Delete glossary",
    deleteText: "Do you want to delete the glossary? All the data will be deleted",
    questionData: "Question data",
    creationDate: "Creation date",
    sectionData: "Section data",
    number: "N",
    answer: "Answer",
    point: "Point",
    noVariants: "No variants",
  },
};
