export default {
    ru: {
        total: "Всего",
        name: 'Продукт',
        inRu: "по русски",
        inEn: "по английски",
        problem: 'Проблема',
        indicationUse: 'Свойства продукта',
        howToUse: 'Советы по применению',
        variants: 'Варианты',
        language: 'Язык',
        picture: 'Картинка',
        composition: 'Состав',
        volume: 'Объем',
        link: 'Вебинар',
        save: 'Сохранить изменения',
        cancel: 'Отменить',
        delete: "Удалить",
        deleteTitle: "Удаление каталога",
        deleteText: "Вы уверенны что хотите удалить каталог? Все данные будут удалены",
        questionData: "Данные вопроса",
        creationDate: "Дата создания",
        catalogData: "Данные каталога",
        phone: "Телефон",
        email: "Эл. адрес",
        personalData: "Личные данные",
        statistics: "Статистика",
    },
    en: {
        total: "Total",
        name: "Name",
        name: 'Name',
        inRu: "in Russian",
        inEn: "in English",
        problem: 'Problem',
        indicationUse: 'Indications for use',
        howToUse: 'How to use',
        variants: 'Variants',
        language: 'Langauge',
        picture: 'Picture',
        composition: 'Composition',
        volume: 'Volume',
        link: 'Link',
        save: 'Save changes',
        cancel: 'Cancel',
        delete: "Delete",
        deleteTitle: "Delete catalogue",
        deleteText: "Do you want to delete the catalogue? All the data will be deleted",
        questionData: "Question data",
        creationDate: "Creation date",
        catalogData: "Catalogue data",
        phone: "Phone number",
        email: "Email",
        personalData: "Personal data",
        statistics: "Statistics",
    }
}